[package]
name = "merge_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.1.0"
json = "0.12.4"
task_executor = { path = "../../common/task_executor" }
tokio = { version = "1.14.0", features = ["rt-multi-thread", "macros"] }
futures = "0.3.7"
exit-future = "0.2.0"
environment = { path = "../../lighthouse/environment" }
execution_layer = { path = "../../beacon_node/execution_layer" }
sensitive_url = { path = "../../common/sensitive_url" }
types = { path = "../../consensus/types" }
