[package]
name = "eth2_ssz_types"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[lib]
name = "ssz_types"

[dependencies]
tree_hash = "0.1.1"
serde = "1.0.116"
serde_derive = "1.0.116"
serde_utils = { path = "../serde_utils" }
eth2_ssz = "0.1.2"
typenum = "1.12.0"
arbitrary = { version = "0.4.6", features = ["derive"], optional = true }
smallvec = "1.6.1"

[dev-dependencies]
serde_json = "1.0.58"
tree_hash_derive = "0.2.0"
