[package]
name = "validator_test_rig"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
eth2 = { workspace = true }
logging = { workspace = true }
mockito = { workspace = true }
regex = { workspace = true }
sensitive_url = { workspace = true }
serde_json = { workspace = true }
slog = { workspace = true }
types = { workspace = true }
