[package]
name = "state_transition_vectors"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beacon_chain = { workspace = true }
ethereum_ssz = { workspace = true }
state_processing = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }

[features]
portable = ["beacon_chain/portable"]
