[package]
name = "simulator"
version = "0.2.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { workspace = true }
env_logger = { workspace = true }
eth2_network_config = { workspace = true }
execution_layer = { workspace = true }
futures = { workspace = true }
kzg = { workspace = true }
node_test_rig = { path = "../node_test_rig" }
parking_lot = { workspace = true }
rayon = { workspace = true }
sensitive_url  = { path = "../../common/sensitive_url" }
serde_json = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
