[package]
name = "system_health"
version = "0.1.0"
edition = { workspace = true }

[dependencies]
lighthouse_network = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
sysinfo = { workspace = true }
types = { workspace = true }
