[package]
name = "validator_http_api"
version = "0.1.0"
edition = { workspace = true }
authors = ["Sigma Prime <contact@sigmaprime.io>"]

[lib]
name = "validator_http_api"
path = "src/lib.rs"

[dependencies]
account_utils = { workspace = true }
beacon_node_fallback = { workspace = true }
bls = { workspace = true }
deposit_contract = { workspace = true }
directory = { workspace = true }
dirs = { workspace = true }
doppelganger_service = { workspace = true }
eth2  = { workspace = true }
eth2_keystore  = { workspace = true }
ethereum_serde_utils = { workspace = true }
filesystem = { workspace = true }
graffiti_file = { workspace = true }
initialized_validators = { workspace = true }
lighthouse_version = { workspace = true }
logging = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true }
sensitive_url = { workspace = true }
serde = { workspace = true }
signing_method = { workspace = true }
slashing_protection = { workspace = true }
slog =  { workspace = true }
slot_clock =  { workspace = true }
sysinfo =  { workspace = true }
system_health =  { workspace = true }
task_executor =  { workspace = true }
tempfile =  { workspace = true }
tokio =  { workspace = true }
tokio-stream =  { workspace = true }
types =  { workspace = true }
url =  { workspace = true }
validator_dir =  { workspace = true }
validator_services =  { workspace = true }
validator_store =  { workspace = true }
warp = { workspace = true }
warp_utils = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
futures = { workspace = true }
itertools = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
